// Backup a committed data snapshot and its referenced evidence. Restore only into an empty folder.
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function safePath(root,relative){if(!/^(store\.json|evidence\/[0-9a-f-]{36})$/.test(relative))throw Error('Invalid backup entry.');return path.join(root,relative);}
function empty(root){if(fs.existsSync(root)&&fs.readdirSync(root).length)throw Error('Choose an empty destination folder.');fs.mkdirSync(root,{recursive:true});}
function backup(source,destination){const bytes=fs.readFileSync(path.join(source,'store.json')),db=JSON.parse(bytes);empty(destination);const files={'store.json':bytes};for(const r of db.runs||[])for(const n of r.readings)for(const e of [n.opening,n.closing])if(e?.photoId){const name='evidence/'+e.photoId;files[name]=fs.readFileSync(safePath(source,name));}const manifest={version:1,createdAt:new Date().toISOString(),files:{}};for(const [name,data]of Object.entries(files)){const target=safePath(destination,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,data);manifest.files[name]=hash(data);}fs.writeFileSync(path.join(destination,'manifest.json'),JSON.stringify(manifest,null,2));return Object.keys(files).length;}
function restore(source,destination){const manifest=JSON.parse(fs.readFileSync(path.join(source,'manifest.json'),'utf8'));if(manifest.version!==1||!manifest.files['store.json'])throw Error('Unsupported backup.');const files=Object.entries(manifest.files).map(([name,expected])=>{const data=fs.readFileSync(safePath(source,name));if(hash(data)!==expected)throw Error('Backup integrity check failed.');return [name,data]});JSON.parse(files.find(([name])=>name==='store.json')[1]);empty(destination);for(const[name,data]of files){const target=safePath(destination,name);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,data);}return files.length;}
if(require.main===module){try{const [action,source,destination]=process.argv.slice(2);if(!source||!destination||!['create','restore'].includes(action))throw Error('Usage: node backup.cjs create|restore SOURCE EMPTY_DESTINATION');const count=(action==='create'?backup:restore)(path.resolve(source),path.resolve(destination));console.log('Verified '+count+' files.');}catch(e){console.error(e.message);process.exitCode=1;}}
module.exports={backup,restore};
