const {dayKey}=require('./dashboard.cjs');
function bad(message){throw Object.assign(new Error(message),{status:400});}
function range(q){const today=dayKey(new Date()),from=q.get('from')||today,to=q.get('to')||today;for(const d of [from,to])if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!Number.isFinite(Date.parse(d))||new Date(d).toISOString().slice(0,10)!==d)bad('Enter valid report dates.');if(from>to)bad('Start date must be before the end date.');return {from,to};}
function reports(db,stationId,q){const dates=range(q),filters=Object.fromEntries(['salesmanId','machineId','shiftId','fuelId'].map(k=>[k,q.get(k)||'']));const runs=(db.runs||[]).filter(r=>r.stationId===stationId&&r.status==='completed'&&r.calculation&&dayKey(r.completedAt)>=dates.from&&dayKey(r.completedAt)<=dates.to&&(!filters.salesmanId||r.salesmanId===filters.salesmanId)&&(!filters.machineId||r.machineId===filters.machineId)&&(!filters.shiftId||(db.assignments||[]).find(a=>a.id===r.assignmentId)?.shiftId===filters.shiftId)&&(!filters.fuelId||r.readings.some(n=>n.fuelId===filters.fuelId)));
const rows=runs.slice().sort((a,b)=>b.completedAt.localeCompare(a.completedAt)).map(r=>({id:r.id,date:dayKey(r.completedAt),completedAt:r.completedAt,salesman:r.snapshot.salesmanName,machine:r.snapshot.machineName,shift:r.snapshot.shiftName,fuelMilli:r.calculation.totalMilli,expectedMinor:r.calculation.expectedMinor,cashMinor:r.calculation.cashMinor,varianceMinor:r.calculation.varianceMinor,variancePercent:r.calculation.expectedMinor?r.calculation.varianceMinor/r.calculation.expectedMinor*100:null,status:r.calculation.varianceMinor<0?'Shortage':r.calculation.varianceMinor>0?'Excess':'Balanced'}));
const totals=rows.reduce((a,r)=>{for(const k of ['fuelMilli','expectedMinor','cashMinor','varianceMinor'])a[k]+=r[k];return a;},{fuelMilli:0,expectedMinor:0,cashMinor:0,varianceMinor:0});
const groups=kind=>{const map=new Map();for(const r of runs){const id=kind==='salesman'?r.salesmanId:kind==='machine'?r.machineId:(db.assignments||[]).find(a=>a.id===r.assignmentId)?.shiftId;const name=r.snapshot[kind+'Name'];const g=map.get(id)||{id,name,shifts:0,fuelMilli:0,expectedMinor:0,cashMinor:0,varianceMinor:0};g.shifts++;g.fuelMilli+=r.calculation.totalMilli;g.expectedMinor+=r.calculation.expectedMinor;g.cashMinor+=r.calculation.cashMinor;g.varianceMinor+=r.calculation.varianceMinor;map.set(id,g);}return [...map.values()]};
const fuels=new Map();for(const r of runs)for(const sale of r.calculation.sales){const g=fuels.get(sale.fuelId)||{id:sale.fuelId,name:r.readings.find(n=>n.nozzleId===sale.nozzleId)?.fuelName||'Fuel',fuelMilli:0,expectedMinor:0};g.fuelMilli+=sale.volumeMilli;g.expectedMinor+=sale.expectedMinor;fuels.set(sale.fuelId,g);}
return {...dates,filters,totals,rows,performance:{salesmen:groups('salesman'),machines:groups('machine'),shifts:groups('shift'),fuels:[...fuels.values()]}};}
function auditReport(db,stationId,q){const dates=range(q);const events=(db.audit||[]).filter(a=>a.stationId===stationId&&dayKey(a.time)>=dates.from&&dayKey(a.time)<=dates.to).slice().reverse().map(a=>({...a,actorName:db.users.find(u=>u.id===a.actor)?.name||'Unknown user'}));return {...dates,events};}
function cells(report){return [['Date (Pakistan time)','Salesman','Machine','Shift','Fuel sold (L)','Expected cash (Rs.)','Cash handover (Rs.)','Variance (Rs.)','Variance (%)','Status','Shift ID'],...report.rows.map(r=>[r.date,r.salesman,r.machine,r.shift,r.fuelMilli/1000,r.expectedMinor/100,r.cashMinor/100,r.varianceMinor/100,r.variancePercent===null?'':Number(r.variancePercent.toFixed(4)),r.status,r.id])];}
function csv(rows){return '\ufeff'+rows.map(row=>row.map(v=>'"'+String(typeof v==='string'&&/^[=+\-@\t\r]/.test(v)?"'"+v:v).replaceAll('"','""')+'"').join(',')).join('\r\n');}
module.exports={reports,auditReport,cells,csv};
